### ISSUE TITLE
Pull in ember-component-focus?

### ISSUE THREAD

**Issue by whastings** [ember-a11y/ember-a11y#14]
@nathanhammond Would you be interested in pulling in my [ember-component-focus](https://github.com/linkedin/ember-component-focus) addon to add to the functionality that ember-a11y offers? We could either pull in component-focus as a dependency and republish its functionality or I could deprecate the addon and you could pull the code in here.

**Comment by nathanhammond** [comment]
Until we have tree-shaking I would rather not bundle a ton of functionality all in one addon. But! I did just create a new organization on GitHub that I'm going to migrate this addon to. You have an invitation to join that organization which would allow you to migrate it there as well.

**Comment by nathanhammond** [comment]
Migrated ember-component focus to the organization, as we continue to identify the best-of-breed solutions we'll include them here. 😄
