### ISSUE TITLE
Breaks apps with ember@2.9.0-beta.1

### ISSUE THREAD

**Issue by kategengler** [ember-a11y/ember-a11y#46]
Breaks app with ember@2.9.0-beta.1
### Reproduction
1. Create an app using ember@2.9.0-beta.1 + ember-a11y
2. Run `ember s`
3. Go to the app in the browser, you'll see a white screen (instead of your app) and in the console an exception about 'Could not find module htmlbars-runtime'

**Comment by nathanhammond** [comment]
Lots more wrong with it than that. It literally doesn't work without doing the dynamically scoped variables stuff.

**Comment by kategengler** [comment]
I'm sure, but this was the most obvious symptom, and I figured I should open something so it's googleable for others.

**Comment by twokul** [comment]
https://github.com/ember-a11y/ember-a11y/pull/48 should address this

**Comment by binhums** [comment]
@kategengler can you verify if the latest (0.1.13) works for you?

**Comment by nathanhammond** [comment]
This is addressed. 😄
