### ISSUE TITLE
Remove `positionalParams`

### ISSUE THREAD

**Issue by twokul** [ember-a11y/ember-a11y#49]
We should likely remove this [line](https://github.com/ember-a11y/ember-a11y/blob/master/app/components/focusing-outlet.js#L14) since there's no good reason not to use latest 1.13.x.

**Comment by nathanhammond** [comment]
Eh, I want it to work out of the box with as many things as possible. We know that it would otherwise be incompatible with these versions, so let's go ahead and continue supporting 'em. Somebody else (hi @ef4!) already did that research for us.

**Comment by ef4** [comment]
More like I made the mistake of putting it on the instance instead of the class in the first place. 😝
