### ISSUE TITLE
Aria 1.1 seems not supported

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [ember-a11y/ember-a11y#51]
using the aria-current attribute gives an error
it has been added to https://www.w3.org/TR/wai-aria-1.1/ specifications 
and was not in Aria 1.0

### Reproduction
1. have a tag with aria-selected attribute : 
`<li aria-selected="false" aria-current="false" data-option-index="0" role="option">...</li>`
2. run the ember-a11y plugin

### Actual
Error "aria-valid-attr" is thrown

### Expected
No error

Is it possible to configure or modify ember-a11y so it does not trigger and error ?

**Comment by Robdel12** [comment]
Is this on the right repo? I don't think ember-a11y does anything but patch the router. Could you be looking for ember-a11y-testing?  :)

**Comment by MelSumner** [comment]
Will close issue since we haven't heard back from OP; assuming that they intended to tag ember-a11y-testing. Please re-open if incorrect.
