### ISSUE TITLE
WCAG issue on ember navigation links

### ISSUE THREAD

**Issue by Vishwaas** [ember-a11y/ember-a11y#52]
This is more of a question than an issue, hoping this was come across by the developers of this addon since this is related to accessibility too.

I was trying to get my ember app wcag compliant using JAWS, an issue which came up was

> This link points to a named anchor "/xyz" within the document, 
> but no anchor exists with that name.
> `<a id="ember635" href="#/abc" class="ember-view">Link Text</a>`

Since ember navigation links use #/pathname, JAWS is expecting an anchor element for the same meaning something like `<div id="abc"></div>`, what is the ideal or expected way to solve this?

**Comment by Robdel12** [comment]
Are you using the location hash?

**Comment by Vishwaas** [comment]
I do not believe that makes a difference, irrespective of the location type in config the links will always have #/pathname, I am not referring to the url in the browser but the actual link elements. Say if you do
`{{#link-to 'abc'}}Link Text{{/link-to}}`
the resulting element will alwahs be `<a href="#/abc">Link Text</a>` irrespective of location type, the location type only affects the way the url is shown

**Comment by Robdel12** [comment]
> if you do `{{#link-to 'abc'}}Link Text{{/link-to}}` the resulting element will always be `<a href="#/abc">Link Text</a>`

I don't think that's true. Using emberobserver as an example since it's a public ember app, all of the links are rendered as normal hrefs. 
![image](https://cloud.githubusercontent.com/assets/2072894/25147361/e5179e3e-243c-11e7-89cc-5eb163b33b4a.png)

**Comment by Vishwaas** [comment]
Sorry yes, when I tried it before I forgot to rebuild the project hence continued to see "#/".
I dont think using history or auto would be an option, is there a solution for using "hash"?

**Comment by Robdel12** [comment]
Sadly I don't think there is :/ We have a general recommendation for not using location hash (see issue #2)

**Comment by nathanhammond** [comment]
Closing this as it is not something that will be addressed by this addon. There is not a solution for `location: hash`.
