### ISSUE TITLE
Discussion: Do we need to test three versions of node?

### ISSUE THREAD

**Issue by Robdel12** [ember-a11y/ember-a11y#57]
I don't think we need run tests in CI for multiple versions of node. It takes forever to get a passing build. 
![image](https://user-images.githubusercontent.com/2072894/29735364-08ce2a3c-89be-11e7-954e-b62dc821f365.png)

Thoughts?

**Comment by nathanhammond** [comment]
We do a bit of weirdness during the build: https://github.com/ember-a11y/ember-a11y/blob/master/index.js

I'm overly conservative and rarely watch builds for insta-publish. Don't truly care. If we're dropping some we should keep Node 4 as that is most likely to break. Closing, you can self-ship a PR to change behavior. 😄
