### ISSUE TITLE
This addon's name is quite confusing

### ISSUE THREAD

**Issue by musaffa** [ember-a11y/ember-a11y#66]
This addon describes itself as `A collection of tools` and its name also suggests such thing. It sounds like the central addon for building accessible Ember application. Actually it is not. Better if it is renamed as `ember-a11y-outlet`.

**Comment by nathanhammond** [comment]
Hey @musaffa! You're not wrong. The original intent of this addon was to provide more than just this one behavior. I'm not intending to change the scope of this addon, and as such, though it is a bit confusing, I don't intend to either:
- change the description.
- change the name.

**Comment by musaffa** [comment]
The irony is that an addon trying to solve a11y issues has a11y problems in itself. In fact, this is one of the very few repositories I've come across whose name and description don't match its actual scope.
