### ISSUE TITLE
Make issue reporting easy inside of the demo application (e.g. AVRGirl Test Pilot)

### ISSUE THREAD

**Issue by nathanhammond** [ember-a11y/ember-a11y#7]
Hey @noopkat! It turns out that testing ember-a11y has similar scaling problems to what you were encountering with AVRGirl. I've started turning tests into a [repeatable script alongside the demo application](http://nathanhammond.github.io/ember-a11y/) but I'd love to make the issue reporting process seamless. Is this something you'd be interested in helping with?

**Comment by noopkat** [comment]
@nathanhammond sign me up. I can see this being a little questionaire thing where a 'did this work?' button might feature at the end of each test section. We can make this feel nice I bet :smile:
