### ISSUE TITLE
"Cannot read property 'routeName' of undefined"

### ISSUE THREAD

**Issue by mehulkar** [ember-a11y/ember-a11y#75]
### Reproduction
1. Install ember-a11y into an Ember 3.10 app
2. transition between routes

### Actual
- error in console

Doesn't seem to "break" the transition, but breaks test cases since it's an unhandled error.

**Comment by mehulkar** [comment]
Issue is here: https://github.com/ember-a11y/ember-a11y/blob/v0.2.1/addon/utils/pivot-route-identifier.js#L17

**Comment by nathanhammond** [comment]
That API is supposed to continue working until 4.0. Arguably this is an upstream bug.

The issue here is that you need to compare the two handlers for identity, I did so by name, I’m unsure if there is another way to do that.

Also, it’s not just a test failure. It is failing to set focus properly if that thing doesn’t exist.

Can review a PR in 24 hours from post if you ping me on discord, or will take a look myself on May 27.

**Comment by mehulkar** [comment]
I started looking at this, but discovered that it wasn't as straightforward as changing the util function, and I also had to go update the references in the focusing-inner component.

@nathanhammond did you take a look yet?

**Comment by rwjblue** [comment]
The shape of `handlerInfo`'s was definitely not public API in any way. Without having tested this locally, I'd guess that we need to do something like:

```js
    let oldHandler = oldHandlers[i].handler || oldHandlers[i].route;
    let newHandler = newHandlers[i].handler || newHandlers[i].route;
	
	
    if (oldHandler.routeName !== newHandler.routeName) {
      return newHandler;
    }
```

**Comment by jrjohnson** [comment]
This continues a discussion in https://github.com/ember-a11y/ember-a11y/issues/73#issuecomment-476965946

> supports all the way back to [Ember] 1.10

Efforts to bring this addon in line with current versions are rejected and community adoption is slowed. Might it be better to stop supporting the very old Ember 1.10 and focus on providing a good experience for versions of Ember that are still actively maintained which would allow using only public APIs?

We're left in a bad position now, if our team wants to move forward with Ember 3.10 and start making the changes needed to take advantage of the new Octane programming models we will have to drop this addon. Should our app be accessible or modern is a choice no team should need to make. There are only bad compromises down that road.

**Comment by patcoll** [comment]
I have a WIP PR that uses the patch above, fixes many tests, and DRYs up the implementation a bit: https://github.com/ember-a11y/ember-a11y/pull/77

It's still not 100% passing, if someone has any availability, I'd welcome contributions
