### ISSUE TITLE
Scroll prevention on programmatic focus with `overflow: auto`

### ISSUE THREAD

**Issue by nathanhammond** [ember-a11y/ember-a11y#9]
We currently prevent the body from scrolling when focus is set programmatically. That covers the majority of use cases but has an edge case when dealing with `overflow: auto` and `overflow: scroll`.

[The code to implement the current behavior can be found here.](https://github.com/nathanhammond/ember-a11y/blob/master/app/components/focusing-outlet.js#L41) We need to write code to make this function as desired for scroll behavior handling:
- [X] at the `body` level,
- [ ] `overflow`'d element level,
- [ ] and for when they're combined.

And tests, of course. :smile:

**Comment by BrianSipple** [comment]
I started digging into this the other day, and I'm envisioning something like a `friends` route where one of the child routes (the only one, so far) is a [list of suggested friends](https://github.com/BrianSipple/ember-a11y/blob/vertical-scrolling-find-friends-page/tests/dummy/app/routes/friends/find.js) where [the `focusing-outlet` is inside of a container](https://github.com/BrianSipple/ember-a11y/blob/vertical-scrolling-find-friends-page/tests/dummy/app/templates/friends.hbs) with `overflow: auto` and has a [fair amount of content to scroll down through](https://github.com/BrianSipple/ember-a11y/blob/vertical-scrolling-find-friends-page/tests/dummy/app/templates/friends/find.hbs)

I didn't get to digging into the mechanics of anything yet -- but that's the WIP.

**Comment by nathanhammond** [comment]
Open a WIP PR! I'd love to follow along on this.

**Comment by BrianSipple** [comment]
@nathanhammond https://github.com/ember-a11y/ember-a11y/pull/30
